name: refresh-db
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://api.scryfall.com/bulk-data' \
          -o ../../db/db.json
